---

environment_name: example
timezone: Europe/Vienna
docker:
  tag: "latest"
  compose_path: "/tmp"
  registry:
    base: "https://registry.example.org"
# docker_registries:
#   - host: registry.example.org
#     user: "someuser"
#     password: "notreal"
#     test_image: "registry.example.org/image:latest"
condor:
  admin: "admin@example.org"
  uid_domain: "cyverse.at"
  filesystem_domain: "cyverse.at"
  collector_name: "example-collector"
  allow_read: ["*.cyverse.at", "161.35.144.75/24,164.92.152.191/24,164.92.152.162/24,164.92.152.187/24"]
  allow_write: ["*.cyverse.at", "161.35.144.75/24,164.92.152.191/24,164.92.152.162/24,164.92.152.187/24"]
  # allow_read: ["*.example.org", "1.2.3.0/24"]
  # allow_write: ["*.example.org", "1.2.3.0/24"]
  exec_dir: "/var/lib/condor/execute"
  # password: "notreal"
  password: "notreal:seemstobemuchtoshort.sothisoneisalongerversionofapassword"

use_overlay: ''

condor_admin: "{{ condor.admin }}"
condor_uid_domain: "{{ condor.uid_domain }}"
condor_filesystem_domain: "{{ condor.filesystem_domain }}"
condor_collector_name: "{{ condor.collector_name }}"
condor_allow_read: "{{ condor.allow_read }}"
condor_allow_write: "{{ condor.allow_write }}"
condor_exec_dir: "{{ condor.exec_dir }}"
condor_password: "{{ condor.password }}"
