---

environment_name: qa
timezone: Europe/Vienna
docker:
  tag: "latest"
  compose_path: "/tmp"
  registry:
    base: "https://registry.example.org"
# docker_registries:
#   - host: registry.example.org
#     user: "someuser"
#     password: "notreal"
#     test_image: "registry.example.org/image:latest"

tmp_condor_domain: "cyverse.at"
tmp_read_write: >-
  ["*.{{ tmp_condor_domain }},127.0.0.1
  {%- for host in groups['all'] -%}
  ,{{ hostvars[host]['ansible_default_ipv4']['address'] }}
  {%- endfor %}"]
condor:
  admin: "grid@tugraz.at"
  uid_domain: "{{ tmp_condor_domain }}"
  filesystem_domain: "{{ tmp_condor_domain }}"
  collector_name: "example-collector"
  allow_write: "{{ tmp_read_write }}"
  allow_read: "{{ tmp_read_write }}"
  exec_dir: "/var/lib/condor/execute/jobs"
  # password: "notreal"
  password: "notreal:seemstobemuchtoshort.sothisoneisalongerversionofapassword"

use_overlay: ''

condor_masuex__condor_admin: "{{ condor.admin }}"
condor_masuex__condor_uid_domain: "{{ condor.uid_domain }}"
condor_masuex__condor_filesystem_domain: "{{ condor.filesystem_domain }}"
condor_masuex__condor_collector_name: "{{ condor.collector_name }}"
condor_masuex__condor_allow_read: "{{ condor.allow_read }}"
condor_masuex__condor_allow_write: "{{ condor.allow_write }}"
condor_masuex__condor_exec_dir: "{{ condor.exec_dir }}"
condor_masuex__condor_password: "{{ condor.password }}"
