---

- name: Common & TimeZone
  hosts: condor
  become: true
  roles:
    - role: timezone
    - role: common

- name: Docker needs
  hosts: condor:!condor_manager
  become: true
  tasks:
  roles:
    - role: docker
    - role: docker-compose

- name: Condor manager
  hosts: condor_manager
  become: true
  roles:
    - role: condor_masuex
      vars:
        condor_role: "central_manager"

- name: Condor submit
  hosts: condor_submit
  become: true
  roles:
    - role: condor_masuex
      vars:
        condor_role: "submit"
    - role: de-condor-launcher
    - role: de-road-runner

- name: Condor worker
  hosts: condor_worker
  become: true
  tasks:
  roles:
    - role: condor_masuex
      vars:
        condor_role: "execute"

- name: Docker stuff
  hosts: condor:!condor_manager
  become: true
  roles:
    - role: de-network-pruner
    - role: de-image-janitor
    - role: de-docker-logging-plugin
    - role: de-porklock

- name: Log into required docker registries
  hosts: condor
  become: true
  become_user: condor
  tasks:
    - command: "docker login -u {{ item.user }} -p {{ item.password | quote }} {{ item.host }}"
      loop: "{{ docker_registries }}"
      when: docker_registries is defined

# vim: set ft=yaml.ansible :
