---
- name: Get master-host
  ansible.builtin.set_fact:
    condor_masuex_master_host: "{{ groups['condor_manager'][0] }}"

- name: Get master-host fqdn
  ansible.builtin.set_fact:
    condor_masuex_master_fqdn: "{{ hostvars[condor_masuex_master_host].ansible_facts.fqdn }}"

- name: Ensure that the execute directory exists
  ansible.builtin.file:
    path: "{{ condor_exec_dir }}"
    state: "directory"
    owner: "condor"
    group: "condor"
    mode: "0755"

- name: Old ver.9 File should not exist
  ansible.builtin.file:
    path: /etc/condor/config.d/00-htcondor-9.0.config
    state: absent
  notify:
    - Common | restart condor

- name: Generate the main configuration file
  ansible.builtin.template:
    src: "etc/condor/config.d/01-role.config.j2"
    dest: "/etc/condor/config.d/01-{{ condor_role }}.config"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Common | restart condor

- name: Generate the execution directory configuration file
  ansible.builtin.template:
    src: "etc/condor/config.d/03-exec-dir.j2"
    dest: "/etc/condor/config.d/03-exec-dir"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Common | restart condor

- name: Store the pool password
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      echo -n "{{ condor_password }}" |
      condor_store_cred add -c -i -
    # TODO: make var
    creates: /etc/condor/passwords.d/POOL
  notify:
    - Common | restart condor

- name: Create token
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      condor_token_create -identity condor@{{ condor_masuex_master_fqdn }} >
      /etc/condor/tokens.d/condor@{{ condor_masuex_master_fqdn }}
    creates: /etc/condor/tokens.d/condor@{{ condor_masuex_master_fqdn }}
  notify:
    - Common | restart condor
