---
# - name: Import the PGP key used by HTCondor
#   ansible.builtin.rpm_key:
#     key: "https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key"
#     state: "present"
#
# - name: Add the YUM repository file
#   ansible.builtin.yum:
#     # name: "https://research.cs.wisc.edu/htcondor/repo/current/htcondor-release-current.el8.noarch.rpm"
#     name: "https://research.cs.wisc.edu/htcondor/repo/current/htcondor-release-current.el7.noarch.rpm"
#     state: "present"
#
# - name: Install Condor
#   ansible.builtin.yum:
#     name: "condor"
#     state: "present"
    # enablerepo: "powertools"
    # enablerepo: "htcondor-previous"

# - name: Install Condor
#   ansible.builtin.yum:
#     name: "condor-all"
#     state: "present"
#     # enablerepo: "powertools"
#     # enablerepo: "htcondor-previous"

- name: Ensure that the execute directory exists
  ansible.builtin.file:
    path: "{{ condor_exec_dir }}"
    state: "directory"
    owner: "condor"
    group: "condor"
    mode: "0755"

- name: Old ver.9 File should not exist
  ansible.builtin.file:
    path: /etc/condor/config.d/00-htcondor-9.0.config
    state: absent
  notify:
    - Common | restart condor

- name: Generate the main configuration file
  ansible.builtin.template:
    src: "etc/condor/config.d/01-role.config.j2"
    dest: "/etc/condor/config.d/01-{{ condor_role }}.config"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Common | restart condor

# - name: Generate the main configuration file
#   ansible.builtin.template:
#     src: "condor_config.local.j2"
#     dest: "/etc/condor/condor_config.local"
#     owner: "root"
#     group: "root"
#     mode: "0644"

# - name: Copy some config-files
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: /etc/condor/
#     owner: root
#     group: root
#     mode: '0755'
#   with_items:
#     - "config.d"
#     - "ganglia.d"
#
# - name: Copy some config-files
#   ansible.builtin.copy:
#     src: condor_config
#     dest: /etc/condor/
#     owner: root
#     group: root
#     mode: '0644'

- name: Generate the execution directory configuration file
  ansible.builtin.template:
    src: "etc/condor/config.d/03-exec-dir.j2"
    dest: "/etc/condor/config.d/03-exec-dir"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Common | restart condor

# - name: Store the pool password
#   ansible.builtin.command: "condor_store_cred -f /var/lib/condor/pool_password -p {{ condor_password | quote }}"
#   when: condor_password != ""

- name: Store the pool password
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      echo -n "{{ condor_password }}" |
      condor_store_cred add -c -i -
    # TODO: make var
    creates: /etc/condor/passwords.d/POOL
  notify:
    - Common | restart condor

- name: Create tocken
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      condor_token_create -identity condor@manager >
      /etc/condor/tokens.d/condor@manager
    # TODO: make var
    creates: /etc/condor/tokens.d/condor@manager
  notify:
    - Common | restart condor
