---
- name: create /var/log/network-pruner
  file: path=/var/log/network-pruner owner=root group=root mode=0755 state=directory

- name: download network-pruner release
  get_url:
    url: "https://github.com/cyverse-de/network-pruner/releases/download/v0.0.9/network-pruner"
    dest: "/usr/local/bin/network-pruner"
    owner: root
    group: root
    mode: "0755"

- include: systemd.yml
