---
- name: create /var/log/condor-launcher
  file: path=/var/log/condor-launcher owner=root group=root mode=0755 state=directory

- name: clone k8s-resources locally
  become: no
  local_action:
    module: git
    repo: ssh://git@gitlab.cyverse.org/core-sw/k8s-resources
    dest: k8s-resources
    version: "{{ {'dev' : 'master', 'uat' : 'beta', 'latest' : 'prod'}[docker.tag] | default(docker.tag) }}"
    accept_hostkey: yes
  run_once: True

- name: copy jobservice.yml to the remote host
  copy:
    src: k8s-resources/resources/configs/{{environment_name}}/jobservices.yml
    dest: /etc/jobservices.yml
    mode: 0644

- name: remove local k8s-resources clone
  become: no
  local_action:
    module: file
    state: absent
    path: k8s-resources
  run_once: True

- name: pull condor-launcher image
  shell: docker pull discoenv/condor-launcher:{{docker.tag}}

- name: install condor-launcher
  shell: docker run --rm -v /usr/local/bin:/condor-launcher --entrypoint "cp" discoenv/condor-launcher:{{docker.tag}} /go/bin/condor-launcher /condor-launcher/condor-launcher

- include: systemd.yml
