---
- name: create /var/log/condor-launcher
  file: path=/var/log/condor-launcher owner=root group=root mode=0755 state=directory

- name: Add jobservices.yml
  ansible.builtin.template:
    src: jobservices.yml.j2
    dest: /etc/jobservices.yml
    owner: root
    group: root
    mode: "0644"

- name: download condor-launcher release
  get_url:
    url: "https://github.com/cyverse-de/condor-launcher/releases/download/v2.21.0/condor-launcher"
    dest: "/usr/local/bin/condor-launcher"
    owner: root
    group: root
    mode: "0755"

- include: systemd.yml
