---
- name: Add repo file
  ansible.builtin.get_url:
    dest: "/etc/yum.repos.d/docker-ce.repo"
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    mode: "0644"
  tags:
    - install

- name: Install the docker compose plugin
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present
  tags:
    - install

- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/bin/docker-compose
    mode: '0755'
  vars:
    docker_compose_version: 2.22.0  # Change this to the desired version