---
- name: Add jobservices.yml
  ansible.builtin.template:
    src: jobservices.yml.j2
    dest: /etc/jobservices.yml
    owner: root
    group: root
    mode: "0644"

- name: download image-janitor release
  get_url:
    url: "https://github.com/cyverse-de/image-janitor/releases/download/v0.0.3/image-janitor"
    dest: "/usr/local/bin/image-janitor"
    owner: root
    group: root
    mode: "0755"

- include: systemd.yml
