---
- name: Install prerequistes
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install repos and packages
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
