---

- name: Import the PGP key used by HTCondor
  ansible.builtin.rpm_key:
    key: "{{ common__redhat_key }}"
    state: "present"

- name: Add the YUM repository file
  ansible.builtin.yum:
    name:
      - "{{ common__redhat_rpm }}"
    skip_broken: true
    state: "present"

- name: Install Condor
  ansible.builtin.yum:
    name: "condor"
    state: "present"
