---
- name: Ensure that tzdata is installed via yum
  become: true
  ansible.builtin.yum:
    name: tzdata
    state: latest

- name: Ensure that tzdata-java is installed via yum
  become: true
  ansible.builtin.yum:
    name: tzdata-java
    state: latest

- name: Link the correct time zone to /etc/localtime
  become: true
  ansible.builtin.file:
    path: /etc/localtime
    state: link
    src: "/usr/share/zoneinfo/{{ timezone }}"
    force: true
    mode: "0644"

- name: Set current time zone in /etc/timezone
  become: true
  ansible.builtin.template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
