---
# - name: Update apt-cache
#   ansible.builtin.apt:
#     # name: "*"
#     # state: latest
#     update_cache: true

- name: Install repos and packages
  tags:
    - install
  block:
    # - name: Add gpg
    #   ansible.builtin.apt:
    #     name:
    #       - gnupg2
    #     state: present

    - name: Add repo key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: >
          deb https://download.docker.com/linux/debian
          {{ ansible_distribution_release }} stable
        filename: docker
        state: present

    - name: Install Docker CLI
      ansible.builtin.apt:
        name:
          - python3-docker
          - docker-ce-cli
          - docker-ce
          - containerd.io
        state: present
        update_cache: true

          # deb [arch={{ ansible_architecture }}
          # signed-by=/etc/apt/keyrings/docker.gpg]
