---
# Users and groups
- name: Users and groups
  tags:
    - config
    - config_user
  block:
    - name: Add the docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add the docker user
      ansible.builtin.user:
        name: docker
        shell: /bin/bash
        groups: docker
        append: true

    - name: Add the condor user to the docker group
      when: "'condor' in group_names"
      ansible.builtin.user:
        name: condor
        groups: docker
        append: true

# Install repos and packages
- name: Install repos and packages
  tags:
    - install
  notify:
    - Restart and enable docker
  block:
    - name: Add repo file
      ansible.builtin.get_url:
        dest: "/etc/yum.repos.d/docker-ce.repo"
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        mode: "0644"

    - name: Install Docker CLI
      ansible.builtin.package:
        name: docker-ce-cli
        state: present

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: present

    - name: Install containerd.io
      ansible.builtin.package:
        name: containerd.io
        state: present

    - name: Install docker-compose plugin
      ansible.builtin.package:
        name: docker-compose-plugin
        state: present
